# Dockerfile built by Jack Crane. - https://jackcrane.rocks
# Build step

FROM node:18 AS build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Deployment step

FROM busybox:1.35 as deploy

RUN adduser -D static
USER static
WORKDIR /home/static

COPY --from=build /usr/src/app/build/ ./

EXPOSE 8888

CMD ["busybox", "httpd", "-f", "-v", "-p", "8888"]